version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: app_dev
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
        - ./db:/var/lib/mysql
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
